version: '3.8'

services:
  backend:
    build: ./backend
    container_name: r2_backend
    restart: unless-stopped
    env_file:
      - .env # Memuat variabel lingkungan dari file .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: r2_frontend
    restart: unless-stopped
    ports:
      - "80:80" # Meneruskan port 80 di host ke port 80 di container Nginx
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge